### PR TITLE
feat: updates via websockets

### LINKED ISSUE #2: Allow updates via http requests
This is a feature request that would allow triggering the mlog watcher in a way does not require writing to the filesystem, which makes integrating it with other tools such as web-based editors (like the ones provided by [mindcode](http://mindcode.herokuapp.com/), [go-mlog](https://vilsol.github.io/go-mlog-web/) and [mlogjs](https://mlogjs.github.io/mlogjs/editor.html)) much more convenient.

The idea is making the mod setup a basic http server that can receive requests that tell it to update the mlog code on the currently selected processor (just like a write to the filesystem would).

### PR DESCRIPTION
**Pull request by JeanJPNM**
Implements update functionality via a websocket connection.
Closes #2.

Todo:
- [x] Define types of messages that the server can receive
- [x] Define config options for the websocket server
- [x] Handle cases where the server's port is already in use

### CODE REVIEW

**Comment by JeanJPNM** [comment]
Here is a test I made with a modified version of the mlogjs web editor


https://github.com/Sharlottes/MlogWatcher/assets/61994401/4df1ba70-d9dc-4b9b-935d-e11e2c2f2d46

**Comment by JeanJPNM** [comment]
The pull request is pretty much done, but both the korean and english bundles require some attention, one needs to be updated and the other needs to be checked to see if it is clear and concise enough.

**Comment by Sharlottes** [comment]
thanks for your contribution! i'll test PR build mod today and merge it. @JeanJPNM

**Comment by Sharlottes** [comment]
@JeanJPNM is your demo released already? i cannot test on your [unreleased mlogjs web editor](https://mlogjs.netlify.app/editor.html)

**Comment by JeanJPNM** [comment]
You have to go to the pull request's preview link: https://deploy-preview-221--mlogjs.netlify.app/editor.html

**Comment by Sharlottes** [comment]
it works on my machine too.
https://github.com/Sharlottes/MlogWatcher/assets/60801210/0c5f024a-f6b3-4e45-8b61-09af5150d762

thanks for your contribution very much. the PR will be merged.

**Pull request merged**
